### ISSUE TITLE
ensure integrity values of notifications are base64 encoded

### ISSUE THREAD

**Issue by tomkralidis** [wmo-im/wis2pilot#106]
Users have reported that some notification messages `properties.integrity.value` values are not base64 encoded (per the [WNM draft](https://wmo-im.github.io/wis2-notification-message/standard/wis2-notification-message-DRAFT.html#_integrity)), even though they should be.  Relevant reference implementations (wis2box, pywis-pubsub) should be updated accordingly.

Many thanks to @allanfrankwork for reporting the issue.

cc @kaiwirt @golfvert

**Comment by tomkralidis** [comment]
Relevant updates/fixes:
- https://github.com/wmo-im/wis2box/pull/484
- https://github.com/wmo-im/pywis-pubsub/pull/28
- https://github.com/wmo-im/wis2-notification-message/pull/55

**Comment by tomkralidis** [comment]
Updates:
- pywis-pubsub 0.5.0 released: https://github.com/wmo-im/pywis-pubsub/releases/tag/0.5.0
- wis2box fix will be part of 1.0b5 release

**Comment by kaiwirt** [comment]
For GC Offenbach and WIS2 Node Offenbach we use the base64 encoding. However we also see WNM without this encoding. Input-wise we support both hex and base64

**Comment by golfvert** [comment]
To be closed.
