### ISSUE TITLE
wisdev.kishou.go.jp server certificate has expired

### ISSUE THREAD

**Issue by allanfrankwork** [wmo-im/wis2pilot#107]
Hi

I've noticed that the messages in the meteo fr global broker points to assets on wisdev.kishou.go.jp (Global Cache Japan?) but wisdev.kishou.go.jp's server certificate has expired. An asset example is https://wisdev.kishou.go.jp/data/wis2/dza/dz/data/core/weather/surface-based-observations/synop/WIGOS_0-20000-0-60672_20230822T090000/WIGOS_0-20000-0-60672_20230822T090000.bufr4

Apologies if this is not correct place to report this - should it be [here](https://github.com/wmo-im/wis2pilot/issues/50) instead?

I would expect clients trying to download assets use certificate validation so their downloading would fail so its important to get this fixed.

Thanks!

**Comment by kaiwirt** [comment]
@KenRJTD Can you have a look?

**Comment by allanfrankwork** [comment]
Server certificate has been replaced and is no longer expired. Closing issue.

Thanks!
