### ISSUE TITLE
Implement Global Broker France

### ISSUE THREAD

**Issue by efucile** [wmo-im/wis2pilot#14]
|Task | Progress | Date       |
| ------------- | ------------- | ------------- |
| Design and develop a GB  | 100% |   |
| Subscribe to WIS2 nodes  |  100%  |    |
| Coordinate with other GBs and GCs  |  100%  |    |
| Provide metrics on system performance and data availability  |50%    |    |

**Comment by Haddouch101** [comment]
Status Summary
The installation is complete. The Global Broker has subscription to all  WIS2 nodes and DWD and JMA Caches.
