### ISSUE TITLE
Implement Global Broker China

### ISSUE THREAD

**Issue by efucile** [wmo-im/wis2pilot#17]
|Task | Progress | Date       |
| ------------- | ------------- | ------------- |
| Design and develop a GB  | 100% |   |
| Subscribe to WIS2 nodes  |  100%  |    |
| Coordinate with other GBs and GCs  | 100%   |    |
| Provide metrics on system performance and data availability  |20%    |    |

**Comment by commology** [comment]
test

**Comment by Haddouch101** [comment]
**Status Summary**
The design is almost complete (more iterative in future as necessary).
The setup of GB servers and services is complete.
The development of companion application is 50% complete.

The MQTT broker software evaluation is almost complete (more performance test in future as necessary).
