### ISSUE TITLE
WP4 - Global Monitoring

### ISSUE THREAD

**Issue by efucile** [wmo-im/wis2pilot#4]
|Task | Progress | Date       |
| ------------- | ------------- | ------------- |
| Design and develop a GM  | 50% | March 2023  |
| Subscribe to GBs  |  60%  |    |
| Coordinate with other GBs, GCs, and GDCs  | 35%   |    |
| Develop metrics and KPIs to monitor the transition to WIS 2.0   | 10%   |    |
| Provide dashboards and statistics on WIS2 services and data exchange     |40%    |   |

**Comment by Haddouch101** [comment]
- the design of the GM will be completed by June 2023
- Interactive exchange with GB France and GC Germany and Tokyo, GDC Canada is planned starting in early March 2023.

**Comment by golfvert** [comment]
See https://github.com/wmo-im/wis2-guide/issues/17

**Comment by golfvert** [comment]
Before INFCOM 3, contact GM centres to get confirmation they'll continue operating the service from 2025 onwards.
