### ISSUE TITLE
clarify availability of technical artifacts

### ISSUE THREAD

**Issue by tomkralidis** [wmo-im/wis2pilot#45]
In addition to documentation, a number of WIS 2.0 technical artifacts (encodings, vocabularies) need to be made available on public infrastructure to enable (at least) validation and de-referencing.

Proposed artifacts and publication workflow/targets:

| Artifact                    | Format | Target                                                                   | Publication workflow        |
|-----------------------------|--------|--------------------------------------------------------------------------|-----------------------------|
| [notification message schema](https://github.com/wmo-im/wis2-notification-message/blob/main/schemas/wis2-notification-message-bundled.json) | JSON (bundled)   | schemas.wmo.int/wnm/1.0/wis2-notification-message-bundled.json | Copy bundled JSON on release |
| [discovery metadata schema](https://github.com/wmo-im/wcmp2/blob/main/schemas/wcmp2-bundled.json)   | JSON (bundled)   | schemas.wmo.int/wcmp/2.0/wcmp2-bundled.json                          | Copy bundled JSON on release |
| [topic hierarchy](https://github.com/wmo-im/wis2-topic-hierarchy)             | CSV    | codes.wmo.int/wis/2.0/topic-hierarchy                                                 | TBD                         |
| [metric hierarchy](https://github.com/wmo-im/wis2-metric-hierarchy)             | CSV    | codes.wmo.int/wis/2.0/metric-hierarchy                                                  | TBD                         |

cc @golfvert @efucile

**Comment by amilan17** [comment]
related to https://github.com/wmo-im/wis2-topic-hierarchy/issues/26

**Comment by kaiwirt** [comment]
I would add the monitoring metrics and the KPI
