### ISSUE TITLE
WP6.3  Hydrology

### ISSUE THREAD

**Issue by efucile** [wmo-im/wis2pilot#5]
|Task | Progress | Date       |
| ------------- | ------------- | ------------- |
| Design and develop a WIS2 node  | NA |   |
| Define datasets and topics  |  60%  | July 2023   |
|  Notify WMO and provide WIS2 node details | NA   |    |
| Provide access to GBs  | 40%   |  May 2023|
| Publish notification through GBs  |0%    |   Sept 2023 |
| Migrate international data exchange to WIS 2.0  |NA   |   |
| Mapping of discovery metadata   |70% | April 2023  |
| Enriching discovery metadata for hydrology   |20% | July 2023  |
| KPIs for hydrology data and metadata   |50% | June 2023  |

**Comment by Haddouch101** [comment]
- Draft topic hierarchy ready to be discussed in the JET-HYDMON meeting in April 2023
- The mapping of WHOS pilots metadata has been completed, and the implementation in the broker to begin
- The integration of WHOS broker and WIS global broker through MQTT is under implementation
- The implementation of OGC API to publish discovery metadata is completed and currently under test
-
