### ISSUE TITLE
Implement Global Broker for WIS2

### ISSUE THREAD

**Issue by golfvert** [wmo-im/wis2pilot#73]
In addition to each issue (one per GB), I think it is useful to have a shared one where we can discuss aspects that are common to all GB and use this place instead of exchanging emails and keep easily tracks of you discussions. 
@Haddouch101 can you please assign this issue to Weiqing, Wang and Kari? Thanks.

**Comment by wqu-bom** [comment]
@golfvert We will start work on GB soon (hopefully from next week). I remembered that you mentioned some docs on setting up GB. Would you be able to share that. What I am looking for is a bit of guidance.

**Comment by golfvert** [comment]
The Global Broker is made of two (almost) independent components:
- a MQTT broker setup. Typically to be chosen between RabbitMQ, EMQX, VerneMQ, Mosquitto. The latter is the simplest to deploy but can't be clustered. So, it would be a SPOF if used. It could be an option though to start quickly something while working in parallel on implementing a more complex solution. RabbitMQ (version 3.11.6 at time of writing) is an open source solution. Not the simplest tool to deploy. Not (yet) MQTT 5.0 compliant (I have been told that a RabbitMQ compliant with MQTT 5.0 should be released toward the middle of this year). These two are open source and free of charge. VerneMQ is a payable solution. No experience in EMQX. I would suggest either Mosquitto (to start quickyl) or RabbtMQ (to start in a clustered mode) to be chose.
- an anti loop feature ahead of the broker. Here https://github.com/golfvert/WIS2-GlobalBroker-NodeRed an example that is used by Météo-France. It also gives the details of what should be done.

A quick (and dirty) solution would be for those not familiar with MQTT broker and no anti-loop tool ready to start with Mosquitto and WIS2-GlobalBroker-NodeRed tool as a start getting familiar with WIS2 solution and introduce redundancy in the design of the pilot. And rapidly to move to a clustered RabbitMQ and another anti-loop solution in eg. python.
For those (CMA) having already a RabbitMQ installation, obviously, no need to "downgrade" to Mosquitto.

**Comment by tomkralidis** [comment]
We should also clarify QoS parameters as well as retention periods (the [WIS2 Guide](https://github.com/wmo-im/wis2-guide) would where these could be documented for clarification).

**Comment by tomkralidis** [comment]
OK: https://github.com/wmo-im/wis2-guide/issues/5
