### ISSUE TITLE
DWD publishing GTS data on cache/a/gts

### ISSUE THREAD

**Issue by maaikelimper** [wmo-im/wis2pilot#81]
When subscribing to the CMA-broker I noted messages being publish on the topic:
cache/a/gts/#

![image](https://github.com/wmo-im/wis2pilot/assets/19169339/59d0c376-0f5e-4ba8-9809-b32224f8316b)

**Comment by kaiwirt** [comment]
Will go and update based on https://github.com/wmo-im/wis2pilot/issues/10

**Comment by antje-s** [comment]
gts_to_wis2_dwd updated to publish to topic
cache/a/wis2/xxg/gts_to_wis2_dwd/[TTAAii]/[CCCC]
for example:
cache/a/wis2/xxg/gts_to_wis2_dwd/IUAD01/EGRR
(instead of the speaking topics of GTStoWIS2 that have been used so far)

**Comment by kaiwirt** [comment]
Closing as done

**Comment by antje-s** [comment]
Updated to publish to origin
origin/a/wis2/xxg/gts_to_wis2_dwd/....
So "Closing as done" would be fine

**Comment by tomkralidis** [comment]
FYI transition guide is now put forth at:

- https://wmo-im.github.io/wis2-transition-guide (live draft)
- https://github.com/wmo-im/wis2-transition-guide (source)
