### ISSUE TITLE
Are Global Caches required to validate the data they cache?

### ISSUE THREAD

**Issue by 6a6d74** [wmo-im/wis2pilot#86]
See #84 as an example of validation. Should Global Caches do any data validation -- or are they just dumb caches? 

Preferred option is that they are dumb caches without business logic. Validation should be done either at source by the WIS2 Node, or by their affiliated GISC in collaboration with the Global Monitor service?

**Comment by kaiwirt** [comment]
In my opinion WIS2 is only moving data around, without actually interpreting the data. A GC for example might cache data but does not know anything about that data format.

Data validation in my opinion is a task for data users that know how to interpret the data. 

I would prefer that in WIS2 data users can report issues to the responsible GISC. GISCs need to track the issues and contact the relevant centers. GM can provide an issue tracker.

**Comment by golfvert** [comment]
No :)

**Comment by 6a6d74** [comment]
Agreed
