### ISSUE TITLE
WP8.2 - WIS2 -> GTS Gateway

### ISSUE THREAD

**Issue by efucile** [wmo-im/wis2pilot#9]
_26 June 2023_
### DECISION
- TTAAii  and CCCC to be added in the message to make it easy to do the mapping from WIS2 to GTS.
- This will not be included in the WIS2 Notification Message standard, it's only for the gateway.
- identify potential RTHs to run the gateway
- [wis2-guide/WIS2-to-GTS-Gateway.adoc at transition · wmo-im/wis2-guide · GitHub](https://github.com/wmo-im/wis2-guide/blob/transition/WIS2-to-GTS-Gateway.adoc)

**Comment by Haddouch101** [comment]
Need to discuss how can we provide WMO members with data from countries that migrate to WIS2 and stop dissemination in GTS

**Comment by Haddouch101** [comment]
ET-W2AT 15-05-2023:

- TTAAii ( and CCCC TBC) to be added in the message to make it easy to do the mapping from WIS2 to GTS.

**Comment by Haddouch101** [comment]
I checked with GTS experts, all of them they confirm the need of both TTAAii and CCCC for the mapping from WIS2 to GTS

**Comment by 6a6d74** [comment]
This approach seems sound. But we need to test two aspects.

1. How easy it will be for WIS2 Nodes to determine the TTAAii associated with a particular data object ... a WIS2 dataset (e.g., all SYNOPs for Italy) may map onto many TTAAii headers; how will centres manage this mapping?
2. That "unbulletinised" messages can be successfully read by message switches -- we proposed to send each data object (GTS message) separately, no longer bundling into bulletins; GTS provides a mechanism to include a numeric tag on a message to indicate it's the n-th part of a bulletin, but keeping track of that number would be hard to do, so we'll just be blasting loads of small messages at existing GTS users. Will this work?

**Comment by kaiwirt** [comment]
We should make clear to fellow GTS users, that with the on-going migration to WIS2 the data they receive on the GTS will change. During the transition phase we try to make the effects on GTS users as small as possible, but it won't be zero.

**Comment by golfvert** [comment]
We need to find the gateways doing the job. Two options:
- all (lost?) RTH to operate such a gateway
- One or two MTN Center to operate the gateways 

@Haddouch101 liaise with RTHs to identify those willing to do it (and the others). The fallback being one or two MTN Center.

**Comment by hhaddouch** [comment]
ET-W2AT Washington:
Action
Meeting with Ján Osuský to discuss  the possibility to provide the WIS2 to GTS Gateway 
Depending on the decision of this meeting, another meeting with CMA, Brazil and UK will be organized
